# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "badguy" do |node|  
    node.vm.box = "gbarbieru/xenial"
    node.vm.network "private_network", ip: "172.16.0.18", netmask: "255.255.255.248"
    node.vm.hostname = "badguy"
    node.vm.provision "shell", inline: "sudo apt update; sudo apt install slowhttptest -y"

    # Send slow GET headers
    # slowhttptest -c 65539 -r 100 -u http://172.16.0.19
  end

  # Monitor bandwidth:
  # speedometer -r eth1 -t eth1
  config.vm.define "target" do |node|
    node.vm.box = "gbarbieru/xenial"
    node.vm.network "private_network", ip: "172.16.0.19", netmask: "255.255.255.248"
    node.vm.hostname = "target"
    node.vm.provision "shell", inline: "sudo apt update; sudo apt install nginx tcpdump speedometer -y"
  end

end
