# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  webserver_install = %q{
    sudo dpkg --configure -a
    sudo apt update
    sudo apt install nginx tcpdump speedometer dnsutils -y
  }

  bind_install = %q{
    sudo dpkg --configure -a
    sudo apt update
    sudo apt install bind9 dnsutils -y
    cp -f /vagrant/db.* /vagrant/named.* /etc/bind/
    sudo service bind9 restart
    echo "nameserver 127.0.0.1" | sudo tee /etc/resolvconf/resolv.conf.d/head
    sudo resolvconf -u
  }

  saddam_install = %q{
    sudo dpkg --configure -a
    sudo apt update
    sudo apt install git python dnsutils -y
    git clone https://github.com/OffensivePython/Pinject.git
    git clone https://github.com/OffensivePython/Saddam.git
    cp -f /vagrant/dns.txt /home/vagrant/Saddam/
    cp -f /home/vagrant/Pinject/pinject.py /home/vagrant/Saddam/
    echo "nameserver 172.16.0.3" | sudo tee /etc/resolvconf/resolv.conf.d/head
    sudo resolvconf -u
  }


  # Use:
  # cd ~/Saddam
  # sudo python Saddam.py -d dns.txt:test.com 172.16.0.2

  # Monitor traffic with:
  # speedometer -r eth1 -t eth1

  config.vm.define "target" do |node|
    node.vm.box = "gbarbieru/xenial"
    node.vm.network "private_network", ip: "172.16.0.2", netmask: "255.255.255.248"
    node.vm.hostname = "target"
    node.vm.provision "shell", inline: webserver_install
  end

  config.vm.define "dns" do |node|
    node.vm.box = "gbarbieru/xenial"
    node.vm.network "private_network", ip: "172.16.0.3", netmask: "255.255.255.248"
    node.vm.hostname = "dns"
    node.vm.provision "shell", inline: bind_install
  end

  config.vm.define "badguy" do |node|
    node.vm.box = "gbarbieru/xenial"
    node.vm.network "private_network", ip: "172.16.0.4", netmask: "255.255.255.248"
    node.vm.hostname = "badguy"
    node.vm.provision "shell", inline: saddam_install
  end
  
end
